"use client";

import Nav from "@components/Nav";
import { store } from "@lib/store";
import "@styles/globals.css";
import { Provider } from "react-redux";
// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <div className="main">
            <div className="gradient" />
          </div>
          <main className="app">
            <Nav></Nav>
            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
}
